### ISSUE TITLE
[dmsm] Missing data model scheme documentation

### ISSUE THREAD

**Issue by FMassin** [swiss-seismological-service/sed-SeisComP-contributions#13]
Hello,

@luca-s @kaestli @gempa-jabe 

The dmsm does not show up in [the data model doc](https://www.seiscomp.de/doc/base/api-python.html). How difficult is it to add? Just a curiosity question in order to be able to do it [for dmvs](https://github.com/SED-EEW/SED-EEW-SeisComP-contributions/issues/19)...

Cheers

Fred

**Comment by luca-s** [comment]
I don't see the documentation in the [sources](https://github.com/swiss-seismological-service/sed-SeisComP-contributions/tree/master/plugins/master/datamodel) . You can try add an example documentation in a similar way as the  other plugins, that is the `descriptions` folder and the `.rst` file inside

**Comment by gempa-jabe** [comment]
The doc is generated from the core datamodel description and dmsm is not part of the core. It can only be added to the eew doc which is not yet done.

**Comment by FMassin** [comment]
Thanks for your responses.

@gempa-jabe : Do you suggest that I should document dmsm and dmvs in [EEW contrib](https://github.com/SED-EEW/SED-EEW-SeisComP-contributions) and not here in SED contrib? Or just dmvs in [EEW contrib](https://github.com/SED-EEW/SED-EEW-SeisComP-contributions) ?

**Comment by gempa-jabe** [comment]
I would document it where it is defined. SM in SED contrib and VS in EEW.

**Comment by FMassin** [comment]
Makes sense ok. Like this?

https://github.com/SeisComP/common/blob/879b778d1db00316b1f4206cb9ad482a5ba067a3/libs/seiscomp/datamodel/dataextent.h#L173-L176

I guess not exactly, because it's already there:
https://github.com/SED-EEW/SED-EEW-SeisComP-contributions/blob/3644da81b54ae4634c8719a94c9d92da1acb5024/libs/seiscomp/datamodel/vs/vs.h#L82

**Comment by gempa-jabe** [comment]
What exactly do you want to achieve? To document the source code?

**Comment by FMassin** [comment]
Document the dmvs (and maybe dmsm?) data model extension in https://www.seiscomp.de/doc/base/api-python.html

**Comment by gempa-jabe** [comment]
You can't document it there. There is no way.

**Comment by FMassin** [comment]
OK.
