### ISSUE TITLE
NonLinLoc: parameters configured from scolv are not applied

### ISSUE THREAD

**Issue by luca-s** [swiss-seismological-service/sed-SeisComP-contributions#16]
Any parameter configured via scolv (see screenshot) is discarded and not applied.

The reason is that the parameters are restored to default by `NLLocator::updateProfile` (see [here](https://github.com/swiss-seismological-service/sed-SeisComP-contributions/blob/3ba7ff887fd86559ecdc6ff152c2f6b51de29680/plugins/locator/nll/nll_locator.cpp#L1256)) before being used in `NLLocator::relocate`.

[By design](https://github.com/swiss-seismological-service/sed-SeisComP-contributions/blob/3ba7ff887fd86559ecdc6ff152c2f6b51de29680/plugins/locator/nll/nll_locator.cpp#L1250), `NLLocator::updateProfile` would skip any re-configuration if the profile to be set is the same as the current one, however that logic was disabled on purpose: see [here](https://github.com/swiss-seismological-service/sed-SeisComP-contributions/blob/3ba7ff887fd86559ecdc6ff152c2f6b51de29680/plugins/locator/nll/nll_locator.cpp#L1239) and [here](https://github.com/swiss-seismological-service/sed-SeisComP-contributions/blob/3ba7ff887fd86559ecdc6ff152c2f6b51de29680/plugins/locator/nll/nll_locator.cpp#L1215).  That introduced this issue. So I wonder if @gempa-jabe remembers anything on this topic, because I don't want to remove the two lines that introduced this bug, without knowing why they were added in the first place.

![image](https://user-images.githubusercontent.com/15273575/231541976-b5fe88cc-ea71-4fbf-b404-cdcb0eb511ff.png)

**Comment by gempa-jabe** [comment]
Actually I cannot remember what exactly that behaviour triggered. I tend to assume that changing this parameters has been tested, especially the difference of EDT and normal mode but maybe I am wrong. Decisions were made almost a decade ago ...

**Comment by luca-s** [comment]
closed by #17
